#!/usr/bin/env bash

git_root="$(git rev-parse --show-toplevel)"
chowner=$(stat --printf='%U:%G' "$git_root")
supp="$git_root/all.supp"

if [ "$PWD" != "$git_root" ]; then
  (echo "Please \"cd\" to \"$git_root\" and run this script again!" >&2)
  exit 1
fi

scons "$1" debug=1 &&              \
  chown -R $chowner build src &&   \
                                   \
  G_SLICE=always-malloc            \
  G_DEBUG=gc-friendly              \
  GLIBCXX_FORCE_NEW=1              \
  valgrind                         \
      --track-origins=yes          \
      --trace-children=yes         \
      --num-callers=50             \
      --track-fds=yes              \
      --leak-check=full            \
      --show-reachable=yes         \
      --malloc-fill=0xE1           \
      --free-fill=0xF1             \
      --suppressions="$supp"       \
  "$@"
